import {
  IMDRadarProductType,
  IMDRadarStation,
  IMDSatelliteChannel,
  IMDRemoteSensingOverview,
} from '@mausam/shared-types';

const IMD_BASE_URL = 'https://mausam.imd.gov.in';

export const RADAR_STATIONS_CATALOG: IMDRadarStation[] = [
  {
    id: 'delhi',
    name: 'Delhi (Mausam Bhawan HQ)',
    state: 'Delhi NCR',
    lat: 28.588,
    lon: 77.221,
    band: 'S-band',
    availableProducts: ['MAX_Z', 'PPI_Z', 'SRI', 'PAC', 'PPV', 'VVP2'],
    latestTimestampIST: 'Latest 10-min Scan',
    productImageUrls: {
      MAX_Z: `${IMD_BASE_URL}/Radar/caz_delhi.gif`,
      PPI_Z: `${IMD_BASE_URL}/Radar/ppi_delhi.gif`,
      SRI: `${IMD_BASE_URL}/Radar/sri_delhi.gif`,
      PAC: `${IMD_BASE_URL}/Radar/pac_delhi.gif`,
      PPV: `${IMD_BASE_URL}/Radar/ppv_delhi.gif`,
      VVP2: `${IMD_BASE_URL}/Radar/vp2_delhi.gif`,
    },
    animationGifUrl: `${IMD_BASE_URL}/Radar/animation/Converted/DLH_MAXZ.gif`,
  },
  {
    id: 'mumbai',
    name: 'Mumbai (Colaba)',
    state: 'Maharashtra',
    lat: 18.892,
    lon: 72.815,
    band: 'S-band',
    availableProducts: ['MAX_Z', 'PPI_Z', 'SRI', 'PAC', 'PPV', 'VVP2'],
    latestTimestampIST: 'Latest 10-min Scan',
    productImageUrls: {
      MAX_Z: `${IMD_BASE_URL}/Radar/caz_mum.gif`,
      PPI_Z: `${IMD_BASE_URL}/Radar/ppi_mum.gif`,
      SRI: `${IMD_BASE_URL}/Radar/sri_mum.gif`,
      PAC: `${IMD_BASE_URL}/Radar/pac_mum.gif`,
      PPV: `${IMD_BASE_URL}/Radar/ppv_mum.gif`,
      VVP2: `${IMD_BASE_URL}/Radar/vp2_mum.gif`,
    },
    animationGifUrl: `${IMD_BASE_URL}/Radar/animation/Converted/BOM_MAXZ.gif`,
  },
  {
    id: 'chennai',
    name: 'Chennai (Port)',
    state: 'Tamil Nadu',
    lat: 13.083,
    lon: 80.294,
    band: 'S-band',
    availableProducts: ['MAX_Z', 'PPI_Z', 'SRI', 'PAC', 'PPV', 'VVP2'],
    latestTimestampIST: 'Latest 10-min Scan',
    productImageUrls: {
      MAX_Z: `${IMD_BASE_URL}/Radar/caz_chn.gif`,
      PPI_Z: `${IMD_BASE_URL}/Radar/ppi_chn.gif`,
      SRI: `${IMD_BASE_URL}/Radar/sri_chn.gif`,
      PAC: `${IMD_BASE_URL}/Radar/pac_chn.gif`,
      PPV: `${IMD_BASE_URL}/Radar/ppv_chn.gif`,
      VVP2: `${IMD_BASE_URL}/Radar/vp2_chn.gif`,
    },
    animationGifUrl: `${IMD_BASE_URL}/Radar/animation/Converted/CHN_MAXZ.gif`,
  },
  {
    id: 'kolkata',
    name: 'Kolkata (Alipore)',
    state: 'West Bengal',
    lat: 22.533,
    lon: 88.331,
    band: 'S-band',
    availableProducts: ['MAX_Z', 'PPI_Z', 'SRI', 'PAC', 'PPV', 'VVP2'],
    latestTimestampIST: 'Latest 10-min Scan',
    productImageUrls: {
      MAX_Z: `${IMD_BASE_URL}/Radar/caz_kol.gif`,
      PPI_Z: `${IMD_BASE_URL}/Radar/ppi_kol.gif`,
      SRI: `${IMD_BASE_URL}/Radar/sri_kol.gif`,
      PAC: `${IMD_BASE_URL}/Radar/pac_kol.gif`,
      PPV: `${IMD_BASE_URL}/Radar/ppv_kol.gif`,
      VVP2: `${IMD_BASE_URL}/Radar/vp2_kol.gif`,
    },
    animationGifUrl: `${IMD_BASE_URL}/Radar/animation/Converted/CAL_MAXZ.gif`,
  },
  {
    id: 'bengaluru',
    name: 'Bengaluru (Devanahalli)',
    state: 'Karnataka',
    lat: 13.201,
    lon: 77.708,
    band: 'C-band',
    availableProducts: ['MAX_Z', 'PPI_Z', 'SRI', 'PAC', 'PPV', 'VVP2'],
    latestTimestampIST: 'Latest 10-min Scan',
    productImageUrls: {
      MAX_Z: `${IMD_BASE_URL}/Radar/caz_blr.gif`,
      PPI_Z: `${IMD_BASE_URL}/Radar/ppi_blr.gif`,
      SRI: `${IMD_BASE_URL}/Radar/sri_blr.gif`,
      PAC: `${IMD_BASE_URL}/Radar/pac_blr.gif`,
      PPV: `${IMD_BASE_URL}/Radar/ppv_blr.gif`,
      VVP2: `${IMD_BASE_URL}/Radar/vp2_blr.gif`,
    },
    animationGifUrl: `${IMD_BASE_URL}/Radar/animation/Converted/BLR_MAXZ.gif`,
  },
  {
    id: 'hyderabad',
    name: 'Hyderabad (Begumpet)',
    state: 'Telangana',
    lat: 17.452,
    lon: 78.471,
    band: 'C-band',
    availableProducts: ['MAX_Z', 'PPI_Z', 'SRI', 'PAC', 'PPV', 'VVP2'],
    latestTimestampIST: 'Latest 10-min Scan',
    productImageUrls: {
      MAX_Z: `${IMD_BASE_URL}/Radar/caz_hyd.gif`,
      PPI_Z: `${IMD_BASE_URL}/Radar/ppi_hyd.gif`,
      SRI: `${IMD_BASE_URL}/Radar/sri_hyd.gif`,
      PAC: `${IMD_BASE_URL}/Radar/pac_hyd.gif`,
      PPV: `${IMD_BASE_URL}/Radar/ppv_hyd.gif`,
      VVP2: `${IMD_BASE_URL}/Radar/vp2_hyd.gif`,
    },
    animationGifUrl: `${IMD_BASE_URL}/Radar/animation/Converted/HYD_MAXZ.gif`,
  },
  {
    id: 'kochi',
    name: 'Kochi (Naval Base)',
    state: 'Kerala',
    lat: 9.941,
    lon: 76.273,
    band: 'C-band',
    availableProducts: ['MAX_Z', 'PPI_Z', 'SRI', 'PAC', 'PPV', 'VVP2'],
    latestTimestampIST: 'Latest 10-min Scan',
    productImageUrls: {
      MAX_Z: `${IMD_BASE_URL}/Radar/caz_koc.gif`,
      PPI_Z: `${IMD_BASE_URL}/Radar/ppi_koc.gif`,
      SRI: `${IMD_BASE_URL}/Radar/sri_koc.gif`,
      PAC: `${IMD_BASE_URL}/Radar/pac_koc.gif`,
      PPV: `${IMD_BASE_URL}/Radar/ppv_koc.gif`,
      VVP2: `${IMD_BASE_URL}/Radar/vp2_koc.gif`,
    },
    animationGifUrl: `${IMD_BASE_URL}/Radar/animation/Converted/KOC_MAXZ.gif`,
  },
  {
    id: 'patna',
    name: 'Patna (Airport)',
    state: 'Bihar',
    lat: 25.591,
    lon: 85.088,
    band: 'S-band',
    availableProducts: ['MAX_Z', 'PPI_Z', 'SRI', 'PAC', 'PPV', 'VVP2'],
    latestTimestampIST: 'Latest 10-min Scan',
    productImageUrls: {
      MAX_Z: `${IMD_BASE_URL}/Radar/caz_pat.gif`,
      PPI_Z: `${IMD_BASE_URL}/Radar/ppi_pat.gif`,
      SRI: `${IMD_BASE_URL}/Radar/sri_pat.gif`,
      PAC: `${IMD_BASE_URL}/Radar/pac_pat.gif`,
      PPV: `${IMD_BASE_URL}/Radar/ppv_pat.gif`,
      VVP2: `${IMD_BASE_URL}/Radar/vp2_pat.gif`,
    },
    animationGifUrl: `${IMD_BASE_URL}/Radar/animation/Converted/PAT_MAXZ.gif`,
  },
  {
    id: 'srinagar',
    name: 'Srinagar (Pir Panjal)',
    state: 'Jammu & Kashmir',
    lat: 34.083,
    lon: 74.797,
    band: 'X-band',
    availableProducts: ['MAX_Z', 'PPI_Z', 'SRI', 'PAC', 'PPV', 'VVP2'],
    latestTimestampIST: 'Latest 10-min Scan',
    productImageUrls: {
      MAX_Z: `${IMD_BASE_URL}/Radar/caz_srn.gif`,
      PPI_Z: `${IMD_BASE_URL}/Radar/ppi_srn.gif`,
      SRI: `${IMD_BASE_URL}/Radar/sri_srn.gif`,
      PAC: `${IMD_BASE_URL}/Radar/pac_srn.gif`,
      PPV: `${IMD_BASE_URL}/Radar/ppv_srn.gif`,
      VVP2: `${IMD_BASE_URL}/Radar/vp2_srn.gif`,
    },
    animationGifUrl: `${IMD_BASE_URL}/Radar/animation/Converted/SRN_MAXZ.gif`,
  },
];

export const SATELLITE_CHANNELS_CATALOG: IMDSatelliteChannel[] = [
  {
    id: 'ir1',
    name: 'Infrared-1 (IR1)',
    wavelength: '10.8 µm',
    description: 'Round-the-clock surface & cloud-top temperature measurement. White shades depict high convective storm clouds.',
    imageUrl: `${IMD_BASE_URL}/Satellite/3Dasiasec_ir1.jpg`,
    animationUrl: `${IMD_BASE_URL}/Satellite/3Dasiasec_ir1.gif`,
    timestampIST: 'INSAT-3DS Live',
  },
  {
    id: 'vis',
    name: 'Visible (VIS)',
    wavelength: '0.65 µm',
    description: 'High-resolution daytime sunlight reflection showing cloud textures, fog banks, and cyclone eye walls.',
    imageUrl: `${IMD_BASE_URL}/Satellite/3Dasiasec_vis.jpg`,
    animationUrl: `${IMD_BASE_URL}/Satellite/3Dasiasec_vis.gif`,
    timestampIST: 'INSAT-3DS Live',
  },
  {
    id: 'wv',
    name: 'Water Vapour (WV)',
    wavelength: '6.7 µm',
    description: 'Mid and upper troposphere moisture circulation, jet streams, and atmospheric river dynamics.',
    imageUrl: `${IMD_BASE_URL}/Satellite/3Dasiasec_wv.jpg`,
    animationUrl: `${IMD_BASE_URL}/Satellite/3Dasiasec_wv.gif`,
    timestampIST: 'INSAT-3DS Live',
  },
  {
    id: 'bt',
    name: 'Cloud Top Brightness (CTBT)',
    wavelength: 'Multi-channel',
    description: 'Color-enhanced convective core heights revealing intense thunderstorm clusters and cloudburst threats.',
    imageUrl: `${IMD_BASE_URL}/Satellite/3Dasiasec_bt.jpg`,
    animationUrl: `${IMD_BASE_URL}/Satellite/3Dasiasec_bt.gif`,
    timestampIST: 'INSAT-3DS Live',
  },
  {
    id: 'rgb',
    name: 'True Color Natural RGB',
    wavelength: 'Composite',
    description: 'Multi-spectral natural composite differentiating ice crystals, snow cover, dust, and water droplet clouds.',
    imageUrl: `${IMD_BASE_URL}/Satellite/3Dasiasec_rgb.jpg`,
    timestampIST: 'INSAT-3DS Live',
  },
];

export function getRemoteSensingOverview(): IMDRemoteSensingOverview {
  return {
    nationalRadarMosaicUrl: `${IMD_BASE_URL}/Radar/MOSAIC/Converted/mosaic.gif`,
    nationalLightningMapUrl: `${IMD_BASE_URL}/lightning/Converted/BT.gif`,
    satelliteChannels: SATELLITE_CHANNELS_CATALOG,
    radarStations: RADAR_STATIONS_CATALOG,
  };
}
